# Generated by Django 4.2.7 on 2023-12-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='patients',
            field=models.ManyToManyField(related_name='receptionists', to='UserManagement.patient'),
        ),
    ]
