# Generated by Django 4.2.7 on 2023-12-05 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_hospital_specialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(default='Scheduled', max_length=20)),
                ('visit_reason', models.CharField(max_length=150)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.hospital')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.specialist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.user')),
            ],
        ),
    ]
